language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

matrix:
  allow_failures:
    - php: 8.1

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - ./tests/run-tests
