language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - ./tests/run-tests